ECommerce.Customer/Controllers/ImageController.cs
using AutoMapper;
using ECommerce.API.DTOs;
using ECommerce.Customer.Services;
using Microsoft.AspNetCore.Mvc;
using Refit;

namespace ECommerce.Customer.Controllers
{
    public class ImageController : Controller
    {

        ImageDTO viewImage = new ImageDTO();
        List<ImageDTO> viewImages = new List<ImageDTO>();
        IImageService imageService =RestService.For<IImageService>("https://localhost:7024/api");


        public ImageController(IMapper mapper)
        {
        }

        // Get all Images
        public async Task<IActionResult> Index()
        {
            try
            {
                viewImages = await imageService.GetImages();
                return View(viewImages);
            }
            catch 
            {
                return RedirectToAction("Error");
            }
        }

        public ViewResult Create() => View();

        // Create new Image
        [HttpPost]
        public async Task<IActionResult> Create(ImageDTO info)
        {
            try
            {
                await imageService.CreateImage(info);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }


        // Get an Image by ID
        public async  Task<IActionResult> Edit(int id)
        {
            try
            { 
                viewImage =await imageService.GetImage(id);        
                return View(viewImage);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        // Edit exist Image
        [HttpPost ]
        public async Task<IActionResult> Edit(int id, ImageDTO info)
        {
            try
            {
                await imageService.UpdateImage(id, info);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        // Delete an Image
        //[HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await imageService.DeleteImage(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        public ViewResult Error() => View();
    }

   
}

ECommerce.Customer/Controllers/ShopController.cs
using ECommerce.Customer.Models;
using ECommerce.Customer.Services;
using ECommerce.SharedDataModels;
using ECommerce.SharedDataModels.Enums;
using Microsoft.AspNetCore.Mvc;
using Refit;
using System.Dynamic;

namespace ECommerce.Customer.Controllers
{
    public class ShopController : Controller
    {
        VegetableDTO viewVegetable = new VegetableDTO();
        RatingDTO rating = new RatingDTO();
        List<VegetableDTO> viewVegetables = new List<VegetableDTO>();
        List<CategoryDTO> viewCategories = new List<CategoryDTO>();
        IVegetableService vegetableService = RestService.For<IVegetableService>("https://localhost:7024/api");
        ICategoryService categoryService = RestService.For<ICategoryService>("https://localhost:7024/api");
        IRatingService ratingService = RestService.For<IRatingService>("https://localhost:7024/api");
        private readonly ILogger<HomeController> _logger;

        public async Task<IActionResult> Index()
        {
            try
            {
                //viewVegetables = await vegetableService.GetVegetables();
                //viewCategories = await categoryService.GetCategories();
                MultiModels customModel = new MultiModels();
                customModel.Vegetables= await vegetableService.GetVegetables();
                customModel.Categories = await categoryService.GetCategories();

                return View(customModel);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }
        public async Task<IActionResult> Detail(int id)
        {
            try
            {
                MultiModels customModel = new MultiModels();
                customModel.Vegetable = await vegetableService.GetVegetable(id);
                customModel.Vegetables = await vegetableService.GetVegetables();
                var ratings = await ratingService.GetRatingsByProductId(id);
                if (ratings.Count() > 0)
                {
                    var ratingSum = ratings.Sum(d => d.RatingNumber);
                    ViewBag.RatingSum = ratingSum;
                    var ratingCount = ratings.Count();
                    ViewBag.RatingCount = ratingCount;
                }
                else
                {
                    ViewBag.RatingSum = 0;
                    ViewBag.RatingCount = 0;
                }
                return View(customModel);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        

        public async Task<IActionResult> Category(int id)
        {
            try
            {
                MultiModels customModel = new MultiModels();
                customModel.Category = await categoryService.GetCategory(id);
                customModel.Categories = await categoryService.GetCategories();
                return View(customModel);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        [ECommerce.API.Authorization.Authorize(UserRole.Customer)]
        public async Task<IActionResult> Rating(int id)
        {
            try
            {
                MultiModels customModel = new MultiModels();
                customModel.Vegetable = await vegetableService.GetVegetable(id);
                customModel.Ratings = await ratingService.GetRatingsByProductId(id);
                var ratings = await ratingService.GetRatingsByProductId(id);
                if (ratings.Count() > 0)
                {
                    var ratingSum = ratings.Sum(d => d.RatingNumber);
                    ViewBag.RatingSum = ratingSum;
                    var ratingCount = ratings.Count();
                    ViewBag.RatingCount = ratingCount;
                }
                else
                {
                    ViewBag.RatingSum = 0;
                    ViewBag.RatingCount = 0;
                }
                return View(customModel);
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Rating(int RatingNumber, int ProductId)
        {
            try
            {
                rating.VegetableId = ProductId;
                rating.RatingNumber = RatingNumber;
                await ratingService.CreateRating(rating);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error");
            }
        }
    }
}

ECommerce.Customer/Controllers/VegetableController.cs
using AutoMapper;
using ECommerce.SharedDataModels;
using ECommerce.Customer.Services;
using Microsoft.AspNetCore.Mvc;
using Refit;

namespace ECommerce.Customer.Controllers
{
    public class VegetableController : Controller
    {
        VegetableDTO viewVegetable = new VegetableDTO();
        List<VegetableDTO> viewVegetables = new List<VegetableDTO>();
        IVegetableService vegetableService =RestService.For<IVegetableService>("https://localhost:7024/api");


        public VegetableController(IMapper mapper)
        {
        }

        // Get all Images
        public async Task<IActionResult> Index()
        {
            try
            {
                viewVegetables = await vegetableService.GetVegetables();
                return View(viewVegetables);
            }
            catch 
            {
                return RedirectToAction("Error");
            }
        }

        //public ViewResult Create() => View();

        //// Create new Image
        //[HttpPost]
        //public async Task<IActionResult> Create(ImageDTO info)
        //{
        //    try
        //    {
        //        await imageService.CreateImage(info);
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return RedirectToAction("Error");
        //    }
        //}


        //// Get an Image by ID
        //public async  Task<IActionResult> Edit(int id)
        //{
        //    try
        //    { 
        //        viewImage =await imageService.GetImage(id);        
        //        return View(viewImage);
        //    }
        //    catch
        //    {
        //        return RedirectToAction("Error");
        //    }
        //}

        //// Edit exist Image
        //[HttpPost ]
        //public async Task<IActionResult> Edit(int id, ImageDTO info)
        //{
        //    try
        //    {
        //        await imageService.UpdateImage(id, info);
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return RedirectToAction("Error");
        //    }
        //}

        //// Delete an Image
        ////[HttpPost]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    try
        //    {
        //        await imageService.DeleteImage(id);
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return RedirectToAction("Error");
        //    }
        //}

        //public ViewResult Error() => View();
    }

   
}

ECommerce.Customer/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce.Customer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.Customer.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/179bca1fd6.js" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="~/css/HomePage.css"/>
    <link rel="stylesheet" href="~/css/Navbar.css"/>
    <link rel="stylesheet" href="~/css/Footer.css"/>
    <link rel="stylesheet" href="~/css/Shop.css"/>
    <link rel="stylesheet" href="~/css/Error.css"/>
</head>
<body>
    <header>
        <nav class="navbar-container">
            <div class="navbar-logo">
                <a class="" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="navbar-logo-img" src="/Images/NavbarLogo.png" alt="navber-logo-img"/>
                </a>
            </div>
            <div class="navbar-links-container">                
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 
                <a class="navbar-link" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a> 
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">About Us</a> 
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">Contact</a> 
            </div>
            <div class="navbar-icons-container">                
                <a class="navbar-link navbar-icon" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-magnifying-glass"></i></a> 
                <a class="navbar-link navbar-icon" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a> 
                @if(Context.Session.GetString("Token")==null){
                <a class="navbar-link navbar-icon" asp-area="" asp-controller="Home" asp-action="Login"><i class="fas fa-user"></i></a> 
                }
                else{
                <a class="navbar-link navbar-icon" asp-area="" asp-controller="Home" asp-action="Logout"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                }
            </div>
            <button class="navbar-extra-container">      
                <i class="fa-solid fa-seedling navbar-extra-icon"></i>
            </button>
        </nav>
    </header>
    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="footer-container">
            
            <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index"><img class="footer-logo-img" src="/Images/NavbarLogo.png" alt="navber-logo-img"/></a> 
            <div class="footer-links">
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 
                <a class="navbar-link" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a> 
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">About Us</a> 
                <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Privacy">Contacts</a>                    
                <a class="navbar-link" asp-area="" asp-controller="Image" asp-action="Index">Image</a>
                <a class="navbar-link" asp-area="" asp-controller="Vegetable" asp-action="Index">Product</a>
            </div>
            <p>Copyright © 2022 by VINZ. All Rights Reserved.</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>